### ISSUE TITLE
Tracking user activity 

### ISSUE THREAD

**Issue by mamu234** [SpaceyaTech/mastori#62]
Tracking daily user data by selecting some basic information about people who visit the app including those who successfully logged in, logged out or who logged in failed. or simply get the overall statistics of those who visited.

**Comment by JimmyTron** [comment]
These are the events we are logging

- [ ] Successful login and logout: (use signals and group, check logs on third party authentication)
- [ ] Failed login: (use signals and group)
- [ ] Create post failure: (use signals to catch the error messages from users)
- [ ] Failed verification: (use signals)
- [ ] Too many request from one account
